## Statistics

In [2]:
import numpy as np

создание матрицы


можно складывать умножать как обычные листы

In [28]:
x=np.array([1,2,])

In [29]:
b=np.array([8,3])

размерность


In [4]:
x.shape

(3,)

In [8]:
y=np.array([
    [1,2],
    [3,4],
    [5,6]
    
])

In [9]:
y.shape


(3, 2)

изменение размерности

In [10]:
y.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

склеивание листов в 1

In [11]:
z=np.array([[1,2,3,],[4,5,6,]])

In [13]:
z.ravel()

array([1, 2, 3, 4, 5, 6])

скалярное произведение векторов

In [30]:
np.dot(x,b)

14

косинус угла между векторами=
скалиярное произведение векторов/
произведение модулей векторов


произведение модулей=перемноженне длинны векторов

In [31]:
lenth=np.linalg.norm(x)
lenth2=np.linalg.norm(b)

In [33]:
np.dot(x,b) / (lenth*lenth2)

0.7327934916262993

если 0 то не близки если 1 то близки

In [69]:
matrix1=np.array([
    [1,2],
    [3,4] 
])


In [70]:
matrix1=np.array([
    [1,2],
    [3,4]      
])

In [71]:
np.dot(matrix1,matrix2)


ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

решение линейных уравнений

3x+y=5

x+6y=20

In [77]:
r=np.array([[3,1],[1,6]])

In [78]:
t=np.array([5,20])

In [79]:
np.linalg.solve(r,t)

array([0.58823529, 3.23529412])